### ISSUE TITLE
Indicator for days that have writing

### ISSUE THREAD

**Issue by tsikatawill** [sunday-studio/ibis#2]
It would be pretty nice if the calendar could indicate days that have some content.
<img width="420" alt="Screenshot 2024-05-17 at 15 47 05" src="https://github.com/sunday-studio/ibis/assets/48873308/8ac03368-79e6-4e90-afe0-86c80fe46219">
Say, I've written some stuff on 9th May, a small indicator should show on the calendar that I have some text there. 
It'll make looking for stuff a bit more convenient as users don't have to struggle to search for their writings.

**Comment by casprine** [comment]
<img width="475" alt="Screenshot 2024-05-17 at 17 53 59" src="https://github.com/sunday-studio/ibis/assets/21961780/a5cc060d-1330-4de8-b228-da4fb9675941">


hey @tsikatawill yeah, that's currently implemented on the `0.1-launch` branch. Thanks for the suggestion
