### ISSUE TITLE
Different themes?

### ISSUE THREAD

**Issue by tsikatawill** [sunday-studio/ibis#3]
I've grown to like dark mode a lot, is there a plan to add dark mode later?
Maybe even have a theme system like Slack where users have a range of themes they can apply through the app.

**Comment by casprine** [comment]
<img width="1233" alt="Screenshot 2024-05-17 at 17 58 23" src="https://github.com/sunday-studio/ibis/assets/21961780/a000597e-277d-428d-adeb-7dddb46ee2cf">

we have dark mode, but I'm not soo sure about a general theming system. maybe later down the line. you can open the command palette with `Commad + K` or click on the search route on the sidebar

**Comment by tsikatawill** [comment]
Awesome, thank you. 
I'm looking forward to the next update :v:
